import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: FoodTruckApi.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Configure Heroku
config :food_truck_api, FoodTruckApiWeb.Endpoint,
  http: [:inet6, port: System.get_env("PORT") || 4000],
  url: [scheme: "https", host: System.get_env("APP_NAME") <> ".herokuapp.com", port: 443],
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  server: true,
  root: ".",
  version: Application.spec(:food_truck_api, :vsn)

config :food_truck_api, FoodTruckApiWeb.Endpoint,
  secret_key_base: System.get_env("SECRET_KEY_BASE")

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
